version: '2'
services:
  Postgres:
    container_name: postgres_databases
    image: postgres:latest
    expose:
      - 5432
    ports:
      - "54321:5432"
    networks:
      - jcoffee
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./local:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      POSTGRES_PASSWORD: 11ea5d12-da53-4ba1-bc7a-6b4a8fd7c741
networks:
  jcoffee:
    external: true
  

volumes:
  postgres: